### ISSUE TITLE
Python Date Formatting for JSON

### ISSUE THREAD

**Issue by jbaikge** [300brand/ocular8#2]
Fix date formatting to include colon in timezone offset. Problem resides in `extract-goose` handler.

```
F0429 12:08:21.569562    1217 elastic-save.go:59] json.Unmarshal(): parsing time ""2015-01-05T17:41:47-0500"" as ""2006-01-02T15:04:05Z07:00"": cannot parse "-0500"" as "Z07:00"
goroutine 1 [running]:
github.com/golang/glog.stacks(0x966500, 0x0, 0x0, 0x0)
    /go/src/github.com/golang/glog/glog.go:766 +0xcd
github.com/golang/glog.(*loggingT).output(0x95e900, 0xc200000003, 0xc20809a0c0, 0x93d8de, 0xf, 0x3b, 0x0)
    /go/src/github.com/golang/glog/glog.go:717 +0x283
github.com/golang/glog.(*loggingT).printf(0x95e900, 0xc200000003, 0x7d5350, 0x14, 0xc208091ea8, 0x1, 0x1)
    /go/src/github.com/golang/glog/glog.go:655 +0x1ef
github.com/golang/glog.Fatalf(0x7d5350, 0x14, 0xc208091ea8, 0x1, 0x1)
    /go/src/github.com/golang/glog/glog.go:1145 +0x64
main.main()
    /go/src/github.com/300brand/ocular8/handlers/elastic-save/elastic-save.go:59 +0xd40
```

**Comment by jbaikge** [comment]
Fixed in v0.2.4 - 8054e10d3c4afe5bdcc58a47d027d78ffae88ad1
